const $=s=>document.querySelector(s);const state={chats:JSON.parse(localStorage.getItem("gchat_chats")||"[]"),current:localStorage.getItem("gchat_current")||null,settings:JSON.parse(localStorage.getItem("gchat_settings")||"{}"),busy:false};
const save=()=>{localStorage.setItem("gchat_chats",JSON.stringify(state.chats));localStorage.setItem("gchat_current",state.current||"");localStorage.setItem("gchat_settings",JSON.stringify(state.settings))};const chat=()=>state.chats.find(x=>x.id===state.current);
function ensure(){if(!chat()){const c={id:crypto.randomUUID(),title:"新對話",messages:[]};state.chats.unshift(c);state.current=c.id;save()}}
function render(){const c=chat();$("#title").textContent=c?.title||"新對話";$("#modelName").textContent=state.settings.model||"未設定模型";const l=$("#chatList");l.innerHTML="";state.chats.forEach(x=>{const b=document.createElement("button");b.className="item"+(x.id===state.current?" active":"");b.textContent=x.title||"新對話";b.onclick=()=>{state.current=x.id;save();render();closeDrawer()};l.appendChild(b)});const box=$("#messages");box.innerHTML="";if(!c||!c.messages.length){box.innerHTML='<div class="empty"><div><div class="avatar">G</div><h1>想聊點什麼？</h1><p>你的私人 AI 對話空間</p></div></div>';return}c.messages.forEach(m=>bubble(m.role,m.content));scroll()}
function bubble(role,text){const r=document.createElement("div");r.className="message "+role;if(role==="assistant"){const a=document.createElement("div");a.className="msgavatar";a.textContent="G";r.appendChild(a)}const b=document.createElement("div");b.className="bubble";b.textContent=text;r.appendChild(b);$("#messages").appendChild(r);return b}const scroll=()=>requestAnimationFrame(()=>$("#messages").scrollTop=$("#messages").scrollHeight);
function openDrawer(){$("#drawer").classList.add("open");$("#shade").classList.remove("hidden")}function closeDrawer(){$("#drawer").classList.remove("open");$("#shade").classList.add("hidden")}
function settings(){["apiBase","apiKey","model"].forEach(k=>$("#"+k).value=state.settings[k]||"");$("#systemPrompt").value=state.settings.systemPrompt??"你是一個有幫助的助手。";$("#temperature").value=state.settings.temperature??.7;$("#settings").showModal()}
function showErr(t){const e=$("#error");e.textContent=t;e.classList.remove("hidden");clearTimeout(showErr.t);showErr.t=setTimeout(()=>e.classList.add("hidden"),7000)}
function resize(){const x=$("#input");x.style.height="auto";x.style.height=Math.min(x.scrollHeight,150)+"px"}function base(u){return u.trim().replace(/\/+$/,"").replace(/\/chat\/completions$/,"")}
async function send(){if(state.busy)return;const i=$("#input"),text=i.value.trim();if(!text)return;if(!state.settings.apiBase||!state.settings.apiKey||!state.settings.model){settings();showErr("請先完成 API 與模型設定。");return}ensure();const c=chat();c.messages.push({role:"user",content:text});if(c.messages.filter(m=>m.role==="user").length===1)c.title=text.slice(0,24);i.value="";resize();render();const out=bubble("assistant","");state.busy=true;$("#send").disabled=true;try{const ms=[];if(state.settings.systemPrompt)ms.push({role:"system",content:state.settings.systemPrompt});ms.push(...c.messages);const r=await fetch(base(state.settings.apiBase)+"/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+state.settings.apiKey},body:JSON.stringify({model:state.settings.model,messages:ms,temperature:Number(state.settings.temperature??.7),stream:true})});if(!r.ok)throw new Error(`HTTP ${r.status}: ${(await r.text()).slice(0,600)}`);if(!r.body)throw new Error("API 沒有提供串流回應。");const rd=r.body.getReader(),d=new TextDecoder();let buf="",ans="";while(true){const q=await rd.read();if(q.done)break;buf+=d.decode(q.value,{stream:true});const lines=buf.split("\n");buf=lines.pop()||"";for(const raw of lines){const line=raw.trim();if(!line.startsWith("data:"))continue;const p=line.slice(5).trim();if(p==="[DONE]")continue;try{const o=JSON.parse(p),delta=o.choices?.[0]?.delta?.content;if(delta){ans+=delta;out.textContent=ans;scroll()}}catch{}}}if(!ans)throw new Error("API 沒有回傳文字內容，請檢查模型與 API 設定。");c.messages.push({role:"assistant",content:ans});save()}catch(e){out.remove();showErr(e.message||String(e))}finally{state.busy=false;$("#send").disabled=false;save()}}
$("#openDrawer").onclick=openDrawer;$("#closeDrawer").onclick=closeDrawer;$("#shade").onclick=closeDrawer;$("#newChat").onclick=()=>{const c={id:crypto.randomUUID(),title:"新對話",messages:[]};state.chats.unshift(c);state.current=c.id;save();render();closeDrawer()};$("#openSettings").onclick=settings;$("#headerSettings").onclick=settings;$("#quickSettings").onclick=settings;$("#closeSettings").onclick=()=>$("#settings").close();$("#saveSettings").onclick=()=>{state.settings={apiBase:$("#apiBase").value.trim(),apiKey:$("#apiKey").value.trim(),model:$("#model").value.trim(),systemPrompt:$("#systemPrompt").value,temperature:Number($("#temperature").value)};save();$("#settings").close();render()};$("#send").onclick=send;$("#input").oninput=resize;$("#input").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}};if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(console.error);ensure();render();