const $=s=>document.querySelector(s);const escapeHtml=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const themes={cream:{name:"奶油米",bg:"#f6f2ec",card:"#fffdf9",ink:"#282522",muted:"#9a948c",line:"#e8e0d6",soft:"#eee8df",user:"#ded5c8",accent:"#2d2925",accent2:"#fff"},blue:{name:"雾蓝",bg:"#eef3f6",card:"#fbfdff",ink:"#263039",muted:"#8c98a1",line:"#dce5ea",soft:"#e5edf1",user:"#d8e5eb",accent:"#355565",accent2:"#fff"},lavender:{name:"雾紫",bg:"#f2eff6",card:"#fcfaff",ink:"#302b36",muted:"#9b93a5",line:"#e3ddea",soft:"#ebe5f0",user:"#e3d9e9",accent:"#554563",accent2:"#fff"},pink:{name:"柔粉",bg:"#f8eff1",card:"#fffafb",ink:"#35292c",muted:"#a18f94",line:"#eadcdf",soft:"#f0e4e7",user:"#ecd8dd",accent:"#65434d",accent2:"#fff"},green:{name:"鼠尾草",bg:"#eff3ee",card:"#fbfdfb",ink:"#29302b",muted:"#909b92",line:"#dce4dd",soft:"#e4ebe5",user:"#d9e4db",accent:"#3e5645",accent2:"#fff"},night:{name:"深夜",bg:"#17191b",card:"#222528",ink:"#f0efeb",muted:"#9ca2a6",line:"#34393d",soft:"#2d3337",user:"#344049",accent:"#f0efeb",accent2:"#17191b"}};
themes.warm={name:"暖白",bg:"#f7f1e8",card:"#fffaf3",ink:"#332b25",muted:"#a09589",line:"#e8ddd0",soft:"#eee3d5",user:"#e6d6c2",accent:"#624c39",accent2:"#fffaf3"};
themes.rain={name:"雨夜",bg:"#1b2025",card:"#242b31",ink:"#edf1f2",muted:"#9ba8b0",line:"#354049",soft:"#2b343b",user:"#354752",accent:"#d9e6eb",accent2:"#1b2025"};
themes.cafe={name:"咖啡馆",bg:"#eee7dd",card:"#fbf7f0",ink:"#3b3028",muted:"#9d8e80",line:"#ddd0c0",soft:"#e7dccd",user:"#dcc7ad",accent:"#684a35",accent2:"#fffaf3"};
themes.mono={name:"黑白",bg:"#f2f2f0",card:"#ffffff",ink:"#202020",muted:"#929292",line:"#dededb",soft:"#e8e8e5",user:"#d9d9d6",accent:"#202020",accent2:"#ffffff"};
const backgrounds={plain:{name:"纯净",value:"none"},paper:{name:"纸张",value:"radial-gradient(circle at 50% -10%,#fffdf9 0,#f6f2ec 45%)"},mist:{name:"柔雾",value:"radial-gradient(circle at 20% 15%,rgba(255,255,255,.85),transparent 35%),radial-gradient(circle at 85% 75%,rgba(220,230,235,.55),transparent 38%)"},lav:{name:"淡紫",value:"radial-gradient(circle at 15% 20%,rgba(225,214,236,.65),transparent 40%),radial-gradient(circle at 80% 75%,rgba(242,231,239,.8),transparent 40%)"},sage:{name:"浅绿",value:"radial-gradient(circle at 20% 20%,rgba(215,230,218,.7),transparent 40%),radial-gradient(circle at 80% 70%,rgba(235,240,226,.8),transparent 42%)"},sun:{name:"晨光",value:"radial-gradient(circle at 70% 15%,rgba(255,231,187,.6),transparent 38%),radial-gradient(circle at 20% 75%,rgba(248,222,210,.55),transparent 40%)"}};
const state={chats:JSON.parse(localStorage.getItem("gchat_chats")||"[]"),current:localStorage.getItem("gchat_current")||null,settings:JSON.parse(localStorage.getItem("gchat_settings")||"{}"),busy:false,selectedBubble:null,recognition:null};
const save=()=>{localStorage.setItem("gchat_chats",JSON.stringify(state.chats));localStorage.setItem("gchat_current",state.current||"");localStorage.setItem("gchat_settings",JSON.stringify(state.settings))};
const chat=()=>state.chats.find(x=>x.id===state.current);
function ensure(){if(!chat()){const c={id:crypto.randomUUID(),title:"新对话",messages:[],createdAt:Date.now()};state.chats.unshift(c);state.current=c.id;save()}}
function applyLook(){const t=themes[state.settings.theme]||themes.cream;const r=document.documentElement;Object.entries(t).forEach(([k,v])=>{if(k!=="name")r.style.setProperty("--"+({bg:"bg",card:"card",ink:"ink",muted:"muted",line:"line",soft:"soft",user:"user",accent:"accent",accent2:"accent2"}[k]||k),v)});r.style.setProperty("--bg-image-opacity",String((state.settings.bgOpacity??18)/100));r.style.setProperty("--bg-image",state.settings.bgCustom?`url(${state.settings.bgCustom})`:(backgrounds[state.settings.bg||"paper"]?.value||backgrounds.paper.value));document.querySelector('meta[name="theme-color"]').setAttribute("content",t.bg);document.body.classList.remove("bubble-soft","bubble-glass","bubble-minimal","bubble-pill");document.body.classList.add("bubble-"+(state.settings.bubble||"soft"));document.body.classList.toggle("no-motion",state.settings.animations===false)}
function avatarHTML(type){const src=type==="user"?state.settings.userAvatar:state.settings.aiAvatar;return src?`<img src="${src}" alt="">`:(type==="user"?"你":"G")}
function formatTime(ts){if(!ts)return"";const d=new Date(ts);if(Number.isNaN(d.getTime()))return"";const now=new Date();const same=d.toDateString()===now.toDateString();return same?d.toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit",hour12:false}):d.toLocaleDateString("zh-TW",{month:"numeric",day:"numeric"})+" "+d.toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit",hour12:false})}
function ensureDates(){let changed=false;const now=Date.now();state.chats.forEach((c,ci)=>{if(!c.createdAt){c.createdAt=now-(ci*3600000);changed=true}c.messages?.forEach((m,mi)=>{if(!m.timestamp){m.timestamp=c.createdAt+(mi*60000);changed=true}})});if(changed)save()}
function welcomeText(){const h=new Date().getHours();if(h<6)return"夜深了，慢慢聊。";if(h<11)return"早安，今天也陪你。";if(h<14)return"午间好，坐下来聊会儿。";if(h<18)return"下午好，今天过得怎么样？";if(h<23)return"晚上好，回来啦。";return"晚安，想说什么都可以。"}
function renderChatList(){const l=$("#chatList");if(!l)return;l.innerHTML="";const now=new Date();const today=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime();const yesterday=today-86400000;let lastGroup="";const groups={};state.chats.forEach(x=>{const t=x.createdAt||0;const key=t>=today?"今天":t>=yesterday?"昨天":"更早";(groups[key]??=[]).push(x)});["今天","昨天","更早"].forEach(key=>{if(!groups[key]?.length)return;const g=document.createElement("div");g.className="chatGroup";g.innerHTML=`<div class="chatGroupTitle">${key}</div>`;groups[key].forEach(x=>{const row=document.createElement("div");row.className="itemRow";const b=document.createElement("button");b.className="item"+(x.id===state.current?" active":"");b.innerHTML=`<span class="itemTitle">${escapeHtml(x.title||"新对话")}</span><span class="itemTime">${formatTime(x.createdAt)}</span>`;b.onclick=()=>{state.current=x.id;save();render();closeDrawer()};const m=document.createElement("button");m.className="itemMore";m.textContent="⋯";m.onclick=e=>{e.stopPropagation();chatMenu(x.id)};row.append(b,m);g.appendChild(row)});l.appendChild(g)});const count=$("#chatCount");if(count)count.textContent=state.chats.length?state.chats.length+" 个":""}
function iFill(text){const i=$("#input");i.value=text;resize();i.focus();document.querySelector("footer")?.scrollIntoView({block:"end",behavior:"smooth"})}
function updateTyping(){const status=$("#typingStatus"),model=$("#modelStatus");if(!status||!model)return;status.classList.toggle("hidden",!state.busy);model.classList.toggle("hidden",state.busy)}
function render(){applyLook();const c=chat();$("#title").textContent=c?.title||"新对话";$("#modelName").textContent=state.settings.model||"未設定模型";$("#headerTime").textContent=c?.messages?.length?" · "+formatTime(c.messages[c.messages.length-1].timestamp):"";updateTyping();const topAvatar=$("#headAvatar"),topMode=state.settings.topAvatar||"user";topAvatar.classList.toggle("is-hidden",topMode==="none");$("#openProfile").classList.toggle("avatar-hidden",topMode==="none");if(topMode!=="none")topAvatar.innerHTML=avatarHTML(topMode);$("#brandAvatar").innerHTML=avatarHTML("ai");renderChatList();const box=$("#messages");box.innerHTML="";if(!c||!c.messages.length){box.innerHTML=`<div class="empty"><div><div class="avatar">${avatarHTML("ai")}</div><span class="welcomeKicker">${welcomeText()}</span><h1>${escapeHtml(state.settings.gName||"G")}</h1><p>${escapeHtml(state.settings.gBio||"你的私人 AI 对话空间")}</p><div class="quickPrompts"><button data-prompt="帮我规划一下今天的安排">规划今天</button><button data-prompt="陪我聊聊，轻松一点">陪我聊聊</button><button data-prompt="帮我整理一下最近的想法">整理思绪</button></div></div></div>`;box.querySelectorAll("[data-prompt]").forEach(b=>b.onclick=()=>{iFill(b.dataset.prompt)});return}c.messages.forEach(m=>bubble(m.role,m.content,false,m.timestamp));scroll()}
function bubble(role,text,streaming=false,timestamp=null){const r=document.createElement("div");r.className="message "+role;const tm=timestamp?document.createElement("span"):null;if(tm){tm.className="msgTime";tm.textContent=formatTime(timestamp)}if(role==="assistant"){const a=document.createElement("div");a.className="msgavatar";a.innerHTML=avatarHTML("ai");r.appendChild(a)}if(role==="user"&&tm)r.appendChild(tm);const b=document.createElement("div");b.className="bubble";b.textContent=text;b.dataset.text=text;r.appendChild(b);if(role==="assistant"&&tm)r.appendChild(tm);if(role==="user"){const a=document.createElement("div");a.className="msgavatar";a.innerHTML=avatarHTML("user");r.appendChild(a)}$("#messages").appendChild(r);bindLongPress(b);return b}
function bindLongPress(el){let timer;const start=e=>{clearTimeout(timer);timer=setTimeout(()=>showBubbleAction(el),550)};const cancel=()=>clearTimeout(timer);el.addEventListener("pointerdown",start);["pointerup","pointercancel","pointerleave"].forEach(x=>el.addEventListener(x,cancel));el.addEventListener("contextmenu",e=>{e.preventDefault();showBubbleAction(el)})}
function showBubbleAction(el){state.selectedBubble=el;const a=$("#bubbleAction");a.classList.remove("hidden");const rect=el.getBoundingClientRect();a.style.left=Math.max(8,Math.min(innerWidth-90,rect.left))+'px';a.style.top=Math.max(8,rect.top-48)+'px'}
function scroll(){requestAnimationFrame(()=>$("#messages").scrollTop=$("#messages").scrollHeight)}
function openDrawer(){$("#drawer").classList.add("open");$("#shade").classList.remove("hidden")}function closeDrawer(){$("#drawer").classList.remove("open");$("#shade").classList.add("hidden")}
function settings(){fillSettings();settingsGoHome();$("#settings").showModal()}
function settingsGoHome(){document.querySelectorAll(".settingsPage").forEach(x=>x.classList.add("hidden"));$("#settingsHome").classList.remove("hidden");$("#settingsBack").classList.add("hidden");$("#settingsTitle").textContent="设置";$("#settingsSubtitle").textContent="G Chat";$("#settingsProfileName").textContent=state.settings.gName||"G";$("#settingsProfileBio").textContent=state.settings.gBio||"你的私人 AI 对话空间";$("#settingsThemeSummary").textContent=themes[state.settings.theme||"cream"]?.name||"奶油米";$("#settingsProfileAvatar").innerHTML=avatarHTML("ai")}
function settingsOpenPage(id){const titles={aiPage:["AI 设置","服务与模型"],personaPage:["G 的设定","个性化聊天空间"],appearancePage:["外观","主题与显示"],avatarPage:["头像","聊天中的头像"],chatPage:["聊天与数据","本地数据管理"]};document.querySelectorAll(".settingsPage").forEach(x=>x.classList.add("hidden"));const page=$("#"+id);if(page)page.classList.remove("hidden");const t=titles[id]||["设置","G Chat"];$("#settingsTitle").textContent=t[0];$("#settingsSubtitle").textContent=t[1];$("#settingsBack").classList.remove("hidden");}
function fillSettings(){$("#myName").value=state.settings.myName||"你";$("#gName").value=state.settings.gName||"G";$("#gBio").value=state.settings.gBio||"你的私人 AI 对话空间";["apiBase","apiKey","model"].forEach(k=>$("#"+k).value=state.settings[k]||"");$("#systemPrompt").value=state.settings.systemPrompt??"你是一个有帮助的助手。";$("#temperature").value=state.settings.temperature??.7;renderModels();renderThemes();renderBackgrounds();renderAvatarPreviews();renderTopAvatar();$("#bgOpacity").value=state.settings.bgOpacity??18;$("#bgOpacityOut").value=(state.settings.bgOpacity??18)+"%";$("#animations").checked=state.settings.animations!==false;renderBubbleStyles()}
function renderModels(){const sel=$("#modelSelect");sel.innerHTML="";const models=[...(state.settings.models||[])];if(state.settings.model&&!models.includes(state.settings.model))models.unshift(state.settings.model);models.forEach(x=>{const o=document.createElement("option");o.value=x;o.textContent=x;sel.appendChild(o)});if(models.length){sel.value=state.settings.model||models[0];sel.onchange=()=>$("#model").value=sel.value}}
function renderThemes(){const box=$("#themeGrid");box.innerHTML="";Object.entries(themes).forEach(([k,t])=>{const b=document.createElement("button");b.className="themeChoice"+(state.settings.theme===k?" active":"");b.style.background=`linear-gradient(135deg,${t.bg} 0 55%,${t.accent} 55% 100%)`;b.innerHTML=`<span>${t.name}</span>`;b.onclick=()=>{state.settings.theme=k;save();applyLook();renderThemes();renderAvatarPreviews()};box.appendChild(b)})}
function renderBackgrounds(){const box=$("#bgGrid");box.innerHTML="";Object.entries(backgrounds).forEach(([k,bg])=>{const b=document.createElement("button");b.className="bgChoice"+(state.settings.bg===k&&!state.settings.bgCustom?" active":"");b.style.background=bg.value==="none"?(themes[state.settings.theme||"cream"].bg):bg.value;b.innerHTML=`<span>${bg.name}</span>`;b.onclick=()=>{state.settings.bg=k;state.settings.bgCustom="";save();applyLook();renderBackgrounds()};box.appendChild(b)})}
function renderBubbleStyles(){$("#animations").onchange=()=>{state.settings.animations=$("#animations").checked;save();applyLook()};document.querySelectorAll("#bubbleGrid [data-bubble]").forEach(b=>b.classList.toggle("active",b.dataset.bubble===(state.settings.bubble||"soft")))}
function renderTopAvatar(){const mode=state.settings.topAvatar||"user";document.querySelectorAll("#topAvatarGrid [data-top-avatar]").forEach(b=>b.classList.toggle("active",b.dataset.topAvatar===mode))}
function renderAvatarPreviews(){$("#userAvatarPreview").innerHTML=avatarHTML("user");$("#aiAvatarPreview").innerHTML=avatarHTML("ai")}
function showErr(t){const e=$("#error");e.textContent=t;e.classList.remove("hidden");clearTimeout(showErr.t);showErr.t=setTimeout(()=>e.classList.add("hidden"),7000)}
function resize(){const x=$("#input");x.style.height="auto";x.style.height=Math.min(x.scrollHeight,150)+"px"}
function base(u){return String(u||"").trim().replace(/\/+$/,"" ).replace(/\/chat\/completions$/i,"")}
function finishBusy(){state.busy=false;const b=$("#send");if(b){b.disabled=false;b.classList.remove("loading")}updateTyping();save()}
function apiHint(){const api=String(state.settings.apiBase||"").trim();if(!api)return"未设置 Base URL";try{const u=new URL(api);return u.origin+u.pathname.replace(/\/+$/,"" )+"/chat/completions"}catch{return"Base URL 格式不正确"}}
async function send(){
 if(state.busy)return;
 const i=$("#input"),text=i.value.trim();
 if(!text)return;
 const api=String(state.settings.apiBase||"").trim(),key=String(state.settings.apiKey||"").trim(),model=String(state.settings.model||"").trim();
 if(!api||!key||!model){showErr("还没有完成 API 设置：请打开设置，检查 Base URL、API Key 和模型。");settings();return}
 let url;
 try{url=base(api)+"/chat/completions";new URL(url)}catch{showErr("API Base URL 格式不正确，请检查地址。");settings();return}
 ensure();const c=chat();
 c.messages.push({role:"user",content:text,timestamp:Date.now()});
 if(c.messages.filter(m=>m.role==="user").length===1)c.title=text.slice(0,24);
 i.value="";resize();save();
 state.busy=true;const sendBtn=$("#send");sendBtn.disabled=true;sendBtn.classList.add("loading");updateTyping();
 try{render()}catch(err){console.error("render before request failed",err)}
 const controller=new AbortController();state._abort=controller;
 const timeout=setTimeout(()=>controller.abort(),20000);
 try{
  const ms=[];
  if(state.settings.systemPrompt)ms.push({role:"system",content:state.settings.systemPrompt});
  ms.push(...c.messages);
  const temp=Number(state.settings.temperature??.7);
  const body={model,messages:ms,stream:false};
  if(Number.isFinite(temp))body.temperature=temp;
  const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json","Authorization":"Bearer "+key},body:JSON.stringify(body),signal:controller.signal,cache:"no-store",credentials:"omit"});
  const raw=await r.text();
  if(!r.ok){let detail=raw;try{const er=JSON.parse(raw);detail=er?.error?.message||er?.message||raw}catch{};throw new Error(`HTTP ${r.status}${detail?": "+String(detail).slice(0,600):""}`)}
  let o;try{o=JSON.parse(raw)}catch{throw new Error("API 返回的不是 JSON。请检查 Base URL 是否为兼容 OpenAI Chat Completions 的接口。")}
  let ans=o?.choices?.[0]?.message?.content??o?.choices?.[0]?.text;
  if(Array.isArray(ans))ans=ans.map(x=>typeof x==="string"?x:(x?.text||x?.content||"")).join("");
  if(ans&&typeof ans!=="string")ans=String(ans);
  if(typeof ans!=="string"||!ans.trim())throw new Error("API 已连接，但没有返回文字内容。请检查模型名称和接口兼容性。\n返回："+JSON.stringify(o).slice(0,300));
  c.messages.push({role:"assistant",content:ans,timestamp:Date.now()});save();
 }catch(e){
  let msg;
  if(e?.name==="AbortError")msg="请求超过 20 秒仍没有返回。\n请检查 Base URL、API Key、模型、余额，以及中转站是否支持浏览器跨域请求。";
  else if(e instanceof TypeError)msg="无法连接 API。\n常见原因：Base URL 错误、网络问题，或接口禁止 GitHub Pages 浏览器跨域（CORS）。";
  else msg=e.message||String(e);
  showErr(msg+"\n请求地址："+apiHint());
 }finally{
  clearTimeout(timeout);if(state._abort===controller)state._abort=null;
  finishBusy();
  try{render()}catch(err){console.error("final render failed",err);updateTyping()}
 }
}

function chatMenu(id){const c=state.chats.find(x=>x.id===id);if(!c)return;const action=prompt("输入操作：1 重命名  2 删除","");if(action==="1"){const n=prompt("新的对话名称",c.title||"新对话");if(n?.trim()){c.title=n.trim().slice(0,40);save();render()}}else if(action==="2"&&confirm("确定删除这个对话吗？")){state.chats=state.chats.filter(x=>x.id!==id);if(state.current===id)state.current=state.chats[0]?.id||null;ensure();save();render()}}
function renameCurrent(){const c=chat();if(!c)return;const n=prompt("新的对话名称",c.title||"新对话");if(n?.trim()){c.title=n.trim().slice(0,40);save();render()}}
function exportChat(){const c=chat();if(!c)return;const text=[`# ${c.title||"新对话"}`,"",...c.messages.map(m=>`${m.role==="user"?"你":"G"}：\n${m.content}\n`)].join("\n");const blob=new Blob([text],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=(c.title||"chat")+".txt";a.click();URL.revokeObjectURL(url)}
function imageToData(file,max=600,quality=.78){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>{const im=new Image();im.onload=()=>{const s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext("2d").drawImage(im,0,0,c.width,c.height);res(c.toDataURL("image/jpeg",quality))};im.onerror=rej;im.src=fr.result};fr.onerror=rej;fr.readAsDataURL(file)})}
async function uploadImage(input,target,max,quality){const f=input.files?.[0];if(!f)return;try{state.settings[target]=await imageToData(f,max,quality);save();applyLook();renderAvatarPreviews();render()}catch{showErr("图片处理失败，请换一张图片。")}}
function exportAll(){const data={version:1,exportedAt:new Date().toISOString(),chats:state.chats,current:state.current,settings:state.settings};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json;charset=utf-8"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="g-chat-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function importAll(file){try{const text=await file.text(),data=JSON.parse(text);if(!data||!Array.isArray(data.chats)||typeof data.settings!=="object")throw new Error("备份文件格式不正确");if(!confirm("恢复备份会覆盖当前聊天记录和设置，确定继续吗？"))return;state.chats=data.chats;state.current=data.current||state.chats[0]?.id||null;state.settings=data.settings||{};ensure();ensureDates();save();render();fillSettings();showErr("备份已恢复")}catch(e){showErr(e.message||"恢复备份失败")}}
function setupVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){showErr("当前 Safari 不支持语音识别，请尝试系统听写或其他浏览器。");return}if(state.recognition){state.recognition.stop();state.recognition=null;$("#mic").classList.remove("active");return}const r=new SR();r.lang="zh-TW";r.continuous=false;r.interimResults=true;state.recognition=r;$("#mic").classList.add("active");r.onresult=e=>{$("#input").value=Array.from(e.results).map(x=>x[0].transcript).join("");resize()};r.onerror=e=>{showErr("语音识别失败："+(e.error||"未知错误"));$("#mic").classList.remove("active");state.recognition=null};r.onend=()=>{$("#mic").classList.remove("active");state.recognition=null}}
$("#openDrawer").onclick=openDrawer;$("#closeDrawer").onclick=closeDrawer;$("#shade").onclick=closeDrawer;$("#newChat").onclick=()=>{const c={id:crypto.randomUUID(),title:"新对话",messages:[],createdAt:Date.now()};state.chats.unshift(c);state.current=c.id;save();render();closeDrawer()};$("#openSettings").onclick=settings;$("#headerSettings").onclick=settings;$("#closeSettings").onclick=()=>$("#settings").close();$("#saveSettings").onclick=()=>{state.settings={...state.settings,myName:$("#myName").value.trim()||"你",gName:$("#gName").value.trim()||"G",gBio:$("#gBio").value.trim()||"你的私人 AI 对话空间",apiBase:$("#apiBase").value.trim(),apiKey:$("#apiKey").value.trim(),model:$("#model").value.trim(),systemPrompt:$("#systemPrompt").value,temperature:Number($("#temperature").value),bgOpacity:Number($("#bgOpacity").value),animations:$("#animations").checked};save();$("#settings").close();render()};$("#addModel").onclick=()=>{const m=$("#model").value.trim();if(!m)return;state.settings.models=[...new Set([...(state.settings.models||[]),m])];save();renderModels();$("#modelSelect").value=m};$("#removeModel").onclick=()=>{const m=$("#model").value.trim();state.settings.models=(state.settings.models||[]).filter(x=>x!==m);save();renderModels()};$("#modelSelect").onchange=()=>$("#model").value=$("#modelSelect").value;$("#renameCurrent").onclick=renameCurrent;$("#exportChat").onclick=exportChat;$("#clearCurrent").onclick=()=>{const c=chat();if(c&&confirm("确定清空当前对话吗？")){c.messages=[];c.title="新对话";save();render();$("#settings").close()}};$("#deleteCurrent").onclick=()=>{const c=chat();if(c&&confirm("确定删除当前对话吗？")){state.chats=state.chats.filter(x=>x.id!==c.id);state.current=state.chats[0]?.id||null;ensure();ensureDates();save();render();$("#settings").close()}};
$("#uploadUserAvatar").onclick=()=>$("#userAvatarFile").click();$("#userAvatarFile").onchange=()=>uploadImage($("#userAvatarFile"),"userAvatar",320,.8);$("#clearUserAvatar").onclick=()=>{state.settings.userAvatar="";save();renderAvatarPreviews();render()};$("#uploadAiAvatar").onclick=()=>$("#aiAvatarFile").click();$("#aiAvatarFile").onchange=()=>uploadImage($("#aiAvatarFile"),"aiAvatar",320,.8);$("#clearAiAvatar").onclick=()=>{state.settings.aiAvatar="";save();renderAvatarPreviews();render()};$("#uploadBg").onclick=()=>$("#bgFile").click();$("#bgFile").onchange=async()=>{const f=$("#bgFile").files?.[0];if(!f)return;try{state.settings.bgCustom=await imageToData(f,1200,.7);save();applyLook();renderBackgrounds();render()}catch{showErr("背景图片处理失败。")}};$("#clearBg").onclick=()=>{state.settings.bgCustom="";save();applyLook();renderBackgrounds();render()};$("#bgOpacity").oninput=e=>{state.settings.bgOpacity=Number(e.target.value);$("#bgOpacityOut").value=e.target.value+"%";save();applyLook()};$("#animations").onchange=()=>{state.settings.animations=$("#animations").checked;save();applyLook()};document.querySelectorAll("#bubbleGrid [data-bubble]").forEach(b=>b.onclick=()=>{state.settings.bubble=b.dataset.bubble;save();renderBubbleStyles();applyLook()});document.querySelectorAll("#topAvatarGrid [data-top-avatar]").forEach(b=>b.onclick=()=>{state.settings.topAvatar=b.dataset.topAvatar;save();renderTopAvatar();render()});$("#openProfile").onclick=()=>{const d=$("#profile");$("#profileAvatar").innerHTML=avatarHTML("ai");$("#profileName").textContent=state.settings.gName||"G";$("#profileBio").textContent=state.settings.gBio||"你的私人 AI 对话空间";$("#profileModel").textContent=state.settings.model||"未设置";$("#profileTheme").textContent=themes[state.settings.theme||"cream"].name;d.showModal()};$("#closeProfile").onclick=()=>$("#profile").close();$("#profileStart").onclick=()=>$("#profile").close();
$("#exportAll").onclick=exportAll;$("#importAll").onclick=()=>$("#importFile").click();$("#importFile").onchange=e=>{const f=e.target.files?.[0];if(f)importAll(f);e.target.value=""};$("#mic").onclick=setupVoice;$("#send").onclick=send;$("#input").oninput=resize;$("#input").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}};$("#copyBubble").onclick=async()=>{if(!state.selectedBubble)return;try{await navigator.clipboard.writeText(state.selectedBubble.dataset.text||state.selectedBubble.textContent);$("#bubbleAction").classList.add("hidden")}catch{showErr("复制失败，请长按文字手动复制。")}};document.addEventListener("pointerdown",e=>{if(!e.target.closest(".bubbleAction")&&!e.target.closest(".bubble"))$("#bubbleAction").classList.add("hidden")});document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tabbody").forEach(x=>x.classList.add("hidden"));b.classList.add("active");$("#"+b.dataset.tab).classList.remove("hidden")});
document.querySelectorAll("[data-settings-page]").forEach(b=>b.onclick=()=>settingsOpenPage(b.dataset.settingsPage));
$("#settingsBack").onclick=settingsGoHome;
$("#toggleApiKey").onclick=()=>{const i=$("#apiKey"),b=$("#toggleApiKey");i.type=i.type==="password"?"text":"password";b.textContent=i.type==="password"?"显示":"隐藏"};
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(console.error);state.settings.theme??="cream";state.settings.bg??="paper";state.settings.models??=[];state.settings.bgOpacity??=18;state.settings.bubble??="soft";state.settings.animations??=true;state.settings.myName??="你";state.settings.gName??="G";state.settings.gBio??="你的私人 AI 对话空间";state.settings.topAvatar??="user";ensure();ensureDates();save();render();
